apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend 
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend 
        name: frontend
        imagePullPolicy: Never
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
